### ISSUE TITLE
Backend deployment checklist

### ISSUE THREAD

**Issue by Youssef1313** [SeniorProject-2023/ocr-app#15]
https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

- [ ] Run `manage.py check --deploy`
- [ ] Load `SECRET_KEY` from env variable `SECRET_KEY = os.environ['SECRET_KEY']`
- [ ] `DEBUG` must be false in production
- [ ] Review everything else in the above link
